### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by SpotComms** [SpotComms/FirejailProfileGenerator#2]
This project is currently licensed under the MIT license. However it pulls content from netblue30/firejail which is licensed as GPL v2 and content from chiraag-nataraj/firejail-profiles which is GPL v3. For now I'll change from MIT to GPL v2. But input from anyone especially @netblue30 and @chiraag-nataraj would be nice.

**Comment by netblue30** [comment]
It is fine with me.

**Comment by chiraag-nataraj** [comment]
No problem. I'll also go ahead and change to GPL v2.
